# Generated by Django 4.2.2 on 2024-09-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_reservation_token_alter_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reservation_token",
        ),
    ]
